{   
    "nome": "Gabriel Fernandes Lima",
    "fantasia": "Gabriel Fernandes Lima",
    "tipo": "C",
    "fisicaJuridica": "F",
    "cpfCnpj": "002130832210",
    "rg": "",
    "ie": "Isento",
    "cep": "49032500",
    "endereco": "Avenida Paulo Silva",
    "numero": "2222",
    "complemento": "Cond Vilag. Ven",
    "bairro": "Farolândia",
    "cidade": "Aracaju",
    "uf": "SE",
    "pais": "BRASIL",
    "telefone1": "79 999997169",
    "telefone2": "",
    "fax": "",
    "entregaCep": "",
    "entregaEndereco": "",
    "entregaNumero": "",
    "entregaComplemento": "",
    "entregaBairro": "",
    "entregaCidade": "",
    "entregaUf": "",
    "entregaPais": "",
    "entregaPontoRef1": "",
    "entregaPontoRef2": "",
    "faturamentoCep": "49032500",
    "faturamentoEndereco": "",
    "faturamentoNumero": "",
    "faturamentoComplemento": "",
    "faturamentoBairro": "",
    "faturamentoCidade": "",
    "faturamentoUf": "",
    "faturamentoPais": "",
    "faturamentoPontoRef1": "",
    "faturamentoPontoRef2": "" 
  }