version: '3'

services:
  app:
    build: .
    command: yarn dev
    ports:
      - '3333:3333'
    environment:
      - DB_HOST_MONGOOSE=database
    volumes:
      - '.:/usr/app'

  database:
    image: mongo
    ports:
      - '27017:27017'

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shop_pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: wpuser
      PMA_PASSWORD: wppass
    restart: always
    ports:
      - 7778:80

networks:
  back:

volumes:
  db:
